// Mocks generated by Mockito 5.4.6 from annotations
// in devicecontroller/test/providers/connection_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:connectivity_plus/connectivity_plus.dart' as _i6;
import 'package:devicecontroller/models/device.dart' as _i4;
import 'package:devicecontroller/services/connectivity_service.dart' as _i5;
import 'package:devicecontroller/services/device_persistence_service.dart'
    as _i2;
import 'package:flutter/services.dart' as _i8;
import 'package:flutter/widgets.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DevicePersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDevicePersistenceService extends _i1.Mock
    implements _i2.DevicePersistenceService {
  MockDevicePersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveDevice(_i4.Device? device) =>
      (super.noSuchMethod(
            Invocation.method(#saveDevice, [device]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Device?> loadDevice() =>
      (super.noSuchMethod(
            Invocation.method(#loadDevice, []),
            returnValue: _i3.Future<_i4.Device?>.value(),
          )
          as _i3.Future<_i4.Device?>);

  @override
  _i3.Future<void> clearDevice() =>
      (super.noSuchMethod(
            Invocation.method(#clearDevice, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveCertFingerprint(String? host, String? sha256Hex) =>
      (super.noSuchMethod(
            Invocation.method(#saveCertFingerprint, [host, sha256Hex]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> loadCertFingerprint(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#loadCertFingerprint, [host]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> clearCertFingerprint(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#clearCertFingerprint, [host]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveSamsungToken(String? host, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveSamsungToken, [host, token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> loadSamsungToken(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#loadSamsungToken, [host]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveLgClientKey(String? host, String? clientKey) =>
      (super.noSuchMethod(
            Invocation.method(#saveLgClientKey, [host, clientKey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> loadLgClientKey(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#loadLgClientKey, [host]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveVizioToken(String? host, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveVizioToken, [host, token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> loadVizioToken(String? host) =>
      (super.noSuchMethod(
            Invocation.method(#loadVizioToken, [host]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i5.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i3.Stream<List<_i6.ConnectivityResult>>.empty(),
          )
          as _i3.Stream<List<_i6.ConnectivityResult>>);

  @override
  void didChangeAppLifecycleState(_i7.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  bool handleStartBackGesture(_i8.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i8.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> didPushRouteInformation(
    _i9.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i7.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i7.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i7.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i3.Future<_i7.AppExitResponse>.value(
              _i7.AppExitResponse.exit,
            ),
          )
          as _i3.Future<_i7.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}
